title: Robyn's Musings
description: >- # this means to ignore newlines until "baseurl:"
  My thoughts on various topics - including cats, astronomy, computer programming and anything 
  else I come up with.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme